### PR TITLE
Added data science resources

### LINKED ISSUE #7: add DATA-SCIENCE resources in the respective README.md file
# About the Issue
You are required to add a **`DATA SCIENCE`** resource in this [README.md](https://github.com/TechBastic/roadmaps/blob/main/Data-Science/README.md) file

### You can add any of the followings :
- Resources
- Communities
- Job Portals

### Screenshot
image

### PR DESCRIPTION
**Pull request by Tashuuuu**
Added data science resources #7

### CODE REVIEW

**Comment by adisuyash** [comment]
I haven't assigned anyone on the Issue to which your Pull Request is linked to as,
I think that the issue should remain opened for others to contribute as well.

That's why I request you to change the Description of your PULL REQUEST
& **dont include** **`Closes/Close/Fixes/Fix`** words in your PR.
Instead add the resources in the PR as well to make it more meaningful.

**Comment by adisuyash** [comment]
@Tashuuuu 
I wish you to make more meaningful PRs & dont add **Fix/Fixes Close/Closes** words in your PRs.
Make sure to do these changes in all the PRs you have raised.

**Comment by Tashuuuu** [comment]
I added data science resources, as mentioned in the issue as well.

**Comment by adisuyash** [comment]
> I added data science resources, as mentioned in the issue as well.

Yes I know.
I have suggested you to make a meaningful PR 
check this [article](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/) for more info

**Pull request merged**
