### PR TITLE
Added full stack resourses

### LINKED ISSUE #3: add FULLSTACK-resources in the respective README.md file
# About the Issue
You are required to add a **`Full Stack Development`** resource in this [README.md](https://github.com/TechBastic/roadmaps/blob/main/FullStack-Development/README.md) file

### You can add any of the followings :
- Resources
- Communities
- Job Portals

### Screenshot
image

### PR DESCRIPTION
**Pull request by Virtual4087**
Added some full stack resources to full stack development dir.

### CODE REVIEW

**Comment by adisuyash** [comment]
I haven't assigned anyone on the Issue to which your Pull Request is linked to as I think that the issue should remain opened for others to contribute as well.

That's why I request you to change the Description of your PULL REQUEST
& **dont include** **`Closes/Close/Fixes/Fix`** words in your PR.
Instead add the resources in the PR as well to make it more meaningful.

**Review by Virtual4087 — COMMENTED** [review]
Ohh ok my bad

**Comment by adisuyash** [comment]
> Ohh ok my bad

No it's not your bad.
You are doing a well, i.e. learning !

**Comment by adisuyash** [comment]
Looks good
Thanks @Virtual4087 ❤️

**Pull request merged**
